#!/bin/bash
#
# Install a Homebrew formula.

################################################################################
# Configuration
################################################################################
# Fail on first error
set -e

################################################################################
# Constants
################################################################################
# Get the current working directory, i.e. the directory of this file. All
# credits for this method goes to this guy https://stackoverflow.com/a/246128.
readonly WORKING_DIRECTORY="$(
  cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd
)"

################################################################################
# Global variables
################################################################################


################################################################################
# Functions
################################################################################
########################################
# Install a Homebrew formula.
#
# Globals:
#   WORKING_DIRECTORY
# Arguments:
#   formula_name Name of the formula to install.
# Returns:
#   None
########################################
docker::install_formula() {
  local formula_name="${1}"

  local formula_directory="$(realpath "${WORKING_DIRECTORY}/../Formula")"
  local formula_basename="${formula_name}.rb"
  local formula_path="${formula_directory}/${formula_basename}"

  HOMEBREW_NO_AUTO_UPDATE=1 brew tap vidavidorra/yard
  echo "Installing ${formula_name} (${formula_path})"
  HOMEBREW_NO_AUTO_UPDATE=1 brew install "${formula_path}" --build-bottle --include-test
  # HOMEBREW_NO_AUTO_UPDATE=1 brew install "/homebrew-yard/Formula/cmake@3.14.0.rb" --build-bottle --include-test
  brew bottle "${formula_name}"
}

################################################################################
# Main
################################################################################
main() {
  docker::install_formula "${@}"
}

main "${@}"
