name: Bottle formulae
on: push

jobs:
  bottle:
    runs-on: ubuntu-latest
    container: vidavidorra/docker-linux:ubuntu1804-master
    strategy:
      matrix:
        formula: [cmake@3.1.0, cmake@3.14.0]
    steps:
      - uses: actions/checkout@v1
      - name Build
        run: |
          npm ci
          npm run build
      - name Bottle ${{ matrix.formula }}
        run: |
          npm run formula:bottle ${{ matrix.formula }}
  create-containter:
    needs: [bottle]
    runs-on: ubuntu-latest
    container: vidavidorra/docker-linux:ubuntu1804-master
    steps:
      - uses: actions/checkout@v1
      - name: Create Docker container
        run: |
          echo "Creating Docker container with bottles installed"
